[target.x86_64-unknown-linux-musl]
pre-build = [
    "apt-get update",
    "apt-get install -y libudev-dev pkg-config musl-dev musl-tools"
]

[target.aarch64-unknown-linux-musl]
pre-build = [
    "apt-get update", 
    "apt-get install -y libudev-dev pkg-config musl-dev musl-tools"
]